### ISSUE TITLE
Improve non-invasive BRMS inspection to determine product vs. community

### ISSUE THREAD

**Issue by chambridge** [quipucords/quipucords#1015]
## Specify type:
- Enhancement

### Priority:
- Medium
___

## Description:
Currently, we don't determine the differences in the BRMS family between community and product using the non-invasive scan for BRMS. We need to improve our data collection to gather the necessary information to determine the product vs. community version.
___

## Acceptance Criteria:

- [ ] Verify that we can determine product vs. community type of BRMS with a non-invasive scan

**Comment by noahl** [comment]
The upstream for BRMS is called Drools. I've been looking through a collection of recent and not-so-recent Drools versions to figure out how to fingerprint it, and I found two key facts:
  - Most of our tasks will not detect Drools, because drools uses different WAR file names than BRMS
  - The tasks that do pick up on drools (because they look for the inner jar files, not the WAR container) should at least not give false positives, because they look for version strings, and all of the Drools version strings that I can see are different from the BRMS/RHDM version strings. (Drools uses the convention we've seen in other JBoss products where the Red Hat product has `-redhat-` in its version string and the community version does not.)

In terms of work items, I think we at least need a Drools test VM to verify what I said above. I will also add a few more Drools versions to our version conversion dictionary, which is a very small amount of work. Beyond that, I don't think we have to do anything else unless we want to put effort into detecting more Drools installations.
