### ISSUE TITLE
Creation of report_version exceeds the CharField max_length

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipucords#1634]
## Bug Description:

The length of report_version exceeds the CharField max_length of 32.

From Logs: 

`psycopg2.DataError: value too long for type character varying(32)`

___

## Acceptance Criteria:

- [ ] Reproduce
- [ ] Change the report_version to a textField()

If we are unable to reproduce, we can close the issue.

**Comment by elyezer** [comment]
I found a way to reproduce this:

Export `QUIPUCORDS_COMMIT` as the latest commit on master. Then build the quipucords container image. After that run the generated image and try to run a scan. It will raise the exception because it is trying to save the report and the version is being created as seen here https://github.com/quipucords/quipucords/blob/master/quipucords/api/common/common_report.py#L26

But the report version on the database is a char field with a max length of 32 and that is what is causing it to raise on the images generated on jenkins but it won't raise locally because `QUIPUCORDS_COMMIT` is set to master. When the commit variable is set to an actual commit hash the commit will already have a size of 40 characters and it will always fail to save.

The report is being created by using this util function https://github.com/quipucords/quipucords/blob/master/quipucords/api/details_report/util.py#L175
