### ISSUE TITLE
Docs: Document full list of actual bash commands that are run on a system when QPC is executed

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#1796]
### Is your feature request related to a problem?
Customers find the list of commands which QPC runs and which ones need elevated privileges helpful but security teams often like to evaluate the exact commands which are run. They can do this by inspecting each role but this is time intensive so it would be great to have a full list of all the executed commands in docs. 

### Describe the solution you'd like

___

## Acceptance Criteria:

- [ ] Verify that users can X Y Z
- [ ] Verify that an expected error is encountered when a user does A B C

___

**Comment by dozdowski** [comment]
If security officers want some kind of enumeration of commands run, we need to make sure it's automatic.  As we start adding product support, or begin doing anything else that touches fact gathering, this could become a real pain to keep in sync.

Something akin to a recursive grep across roles in our repo, spitting out the "raw" line from each task entry is about at the level of what I'd agree to.  @jlprevatt what's your take on how to make that sec-officer friendly?  And @mdvickst does this feel sufficient to you?

**Comment by mdvickst** [comment]
makes sense to me to have it be automated, and the raw commands is all they're looking for anyway. Maybe this is part of the build process to grep for the raw commands and update the docs with a list?

**Comment by kholdaway** [comment]
Pulling out all the raw commands should be fairly easy (scripted).  Some of them are pretty hairy, but I assume they will want the exact commands.  Seem reasonable?

**Comment by mdvickst** [comment]
Sounds great to me!

**Comment by jlprevatt** [comment]
RE the docs part of the question:

Dan is correct that this could get tricky to maintain if the information was added directly to the docs. If we get to the point that we are using the RH CCS build and publishing processes/tools, the overhead involved in keeping this up to date could get costly. If we start translation, there might be restrictions put on how often the documentation could be rebuilt (even if all we are changing is a file that is full of commands).

If we were already an established Red Hat product with a full customer portal presence, including a docs page, here is what I would recommend:

- The docs would include intro material about the fact that we make a list of the exact commands run during a scan available for inspection by your security department. That section would end with a link.
- The actual list of commands would not appear in the documentation.
- The link would go to a customer portal document that contains the list. That would be much easier to update on a more frequent basis if the commands get tweaked a lot. It also bypasses a lot of the docs build/publish overhead (someone still has to revise/publish the customer portal doc, though) and any translation overhead.

But, because we are not yet an established Red Hat product and don't have an official customer portal presence, what else can we do? 

- The docs *could* still include intro material and a link, and not contain the actual list of commands.
- The output of the grep action that is being discussed *could* go into a separate file (not the docs files) in the code.
- The link *could* go to that file.
- If that file is just updated automagically at build time, then it removes even more overhead.
- I don't know if that might be a better overall solution than the customer portal doc above...but I also don't know how "correct" that is as a long-term solution. I would have to ask around in CCS.

**Comment by dozdowski** [comment]
Let's make the assumption that we get an official presence somewhere.  Let's assume Steve is going to centralize docs across the MBU's current project.  Let's assume there are Summit things afoot, and because of that we can get something out of Steve in a timely manner.

If this is all true, I like that latter option.  Automating collation of the raw commands from each task in our catalog of roles sounds like the most reasonable thing to do.

**Comment by kholdaway** [comment]
Issue moved to [quipucords/quipudocs #49](https://github.com/quipucords/quipudocs/issues/49) via [**ZenHub**](https://www.zenhub.com/)
