### ISSUE TITLE
Investigate why we need drf-url-filters as it is not in fedora

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#1946]
## Feature description:
Quipucords uses drf-url-filters==0.5.1 however Fedora does not contain this package.  Investigate why we need it and if we can remove it now that we use Django 2.0.

**Comment by myersCody** [comment]
The `drf-url-filters` package will apply filters on drf queryset, and it also has the ability to support validations on incoming query params & their values. However, after doing a search for `import filter` I could only find it used in one place inside of quipucords inside of  [api/credential/view.py](https://github.com/quipucords/quipucords/blob/master/quipucords/api/credential/view.py#L31)

It was added in this [pull request](https://github.com/quipucords/quipucords/pull/51/files) and although the `CredentialViewSet` does have the mixin passed in as a [parameter](https://github.com/quipucords/quipucords/blob/master/quipucords/api/credential/view.py#L99), it is unclear to if the mixin actually applies any filters or validation to the the credential. The reason I believe that it is being unused is because we don't actually pass any of the `filter.x` elements into the filter backends.

For example current credential backend filters:

	`filter_backends = (DjangoFilterBackend, OrderingFilter)`

instead of something like:

	`filter_backends = (filters.OrderingFilter,)`

Considering that none of our other views use the `drf-filters` I believe that this packge can be removed from the code & requirements.txt.
