### ISSUE TITLE
Cut quipucords server 0.9.2 release

### ISSUE THREAD

**Issue by kholdaway** [quipucords/quipucords#2017]
## Feature description:
Cut quipucords server 0.9.2 release

**Comment by myersCody** [comment]
# Documentation
Documentation for [Quipucords 0.9.2](https://quipucords.readthedocs.io/projects/quipucords/en/0.9.2/)

# Features
- [Issue 2012](https://github.com/quipucords/quipucords/issues/2012) - Add system_purpose json to the insights report
- [Issue 1970](https://github.com/quipucords/quipucords/issues/1970) - Add the ability for Quipucords to gather public cloud facts
- [Issue 1978](https://github.com/quipucords/quipucords/issues/1978) - Investigate, size, design method to detect public cloud deployments via Quipucords scans
- [Issue 1971](https://github.com/quipucords/quipucords/issues/1971) - Quipucords can report facts indicating AWS as host for a VM
- [Issue 1972](https://github.com/quipucords/quipucords/issues/1972) - Quipucords can report facts indicating Azure as host for VM
- [Issue 1973](https://github.com/quipucords/quipucords/issues/1973) - Quipucords can report facts indicating GCP as host for a VM
- [Issue 2018](https://github.com/quipucords/quipucords/issues/2018) - Create a data integrity hash for the reports provided by the /reports endpoint
- [Issue 2009](https://github.com/quipucords/quipucords/issues/2009) - Determine number of users on Linux OS
- [Issue 2029](https://github.com/quipucords/quipucords/issues/2029) - Add cpu_hyperthreading value to the deployments report
- [Issue 1976](https://github.com/quipucords/quipucords/issues/1976) - Add a query param to mask sensitive report data
- [PR 2031](https://github.com/quipucords/quipucords/pull/2031) - Update the requirements before release


# Bugs
- [Issue 2004](https://github.com/quipucords/quipucords/issues/2004) - Quipucords statistical counts off due to relaxed scan job failure handling
- [Issue 2020](https://github.com/quipucords/quipucords/issues/2020) - Added check for case where deployments report produces no valid insights hosts
- [Issue 1977](https://github.com/quipucords/quipucords/pull/2028) - Add bounds checking for dmi_system_uuid

# UI Bugs and Features
[Quipucords UI changelog for 0.9.1 release](https://github.com/quipucords/quipucords-ui/blob/master/CHANGELOG.md#091-2019-08-14)

**Comment by kholdaway** [comment]
@myersCody  I updated the docs link and the link to the UI change log.
