### ISSUE TITLE
Should requests with extra data get told their data is being ignored?

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#205]
So, in general, it seems that the server ignores any extra data provided in a POST or PUT, and if all other necessary data is there it is "happy" and sends back a 200 or 201 depending on the endpoint.

@elyezer can you see any downside to this?

Here is an example (assuming there is a credential with id 1 on the server):
```ipython
In [86]:
requests.request('POST', 'http://localhost:8000/api/v1/profiles/networks/', 
    data={
             'credentials': [1],
             'extra': 'foo',
             'hosts': ['localhost'],
             'name': 'test1',
             'ssh_port': 22
    }
)

Out[86]: <Response [201]>
```

**Comment by elyezer** [comment]
I don't recall seeing any API warning about extra data being passed. I don't know much about API design but I think just ignoring is OK. I will do some research and try to find something about it.

By the way, this is a good point.

**Comment by kholdaway** [comment]
Given the data is not part of the API, I don't see a reason to error out.  In general, REST API will ignore extra fields.  I don't see this as a bug.  Its benign to give me too much information.

**Comment by noahl** [comment]
I would lean towards erroring. If someone is sending an extra data field,
there's a good chance they meant to put that data in a field we would
recognize and are making a mistake. It's easier to debug that if we error
when we see the wrong field, as opposed to silently accepting it and
letting them try to figure out why Sonar isn't behaving as expected.

**Comment by elyezer** [comment]
I talked to @ichimonji10 and he provided a really interesting point, he said:

I'd recommend that you return an error if extra, unsupported fields are sent in a request. I see at least one major argument in favor of allowing unsupported fields: allowing unsupported fields allows the API to grow in the future without breaking existing clients. However, I don't buy the "allows future growth" argument for two reasons:

* Accepting malformed requests may lead to clients that actually *rely on* invalid data being ignored.
* Accepting malformed requests makes it hard for users to learn when they're doing something wrong and to fix their mistakes. This was a major pain point I encountered with Satellite 6's search APIs. I was never able to properly test Satellite 6's search APIs because they are undocumented, and because the liberally accept any and all searches, regardless of whether the searches are valid or not. It was infuriating.

Let me expand on that "rely on invalid behaviour" argument. Imagine an API endpoint that allows a client to search for users. Initially, the API allows clients to search for users based only on names, like so:

```
GET /api/v1/users?name="alice"
```

Now, imagine that a client doesn't understand this, and they issue the following request to see if alice is an administrator (yes, this is an awkward way of doing things, but it's also a valid way of doing things):

```
GET /api/v1/users?name="alice"&groups=['admin']
```

As mentioned earlier, clients can only search for users based on name. The "groups" argument is ignored. The list of search results always includes "alice," so the client thinks that she's an administrator, regardless of whether she actually is. Now, what happens when the API is expanded, and support for the "groups" argument is added, but the syntax used is wrong, and clients should actually use double quotes:

```
GET /api/v1/users?name="alice"&groups=["admin"]
```

What happens now? Will the "groups" argument be ignored, and "alice" will still be returned? Will the single quotes silently be converted to double quotes, and therefore the search will proceed? Will an error be returned, because the syntax is wrong? I think that returning an error when the user does something incorrect actually helps to ensure the long-term longevity of an API as it changes.

An HTTP 400 response code might be appropriate:

> The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax, size too large, invalid request message framing, or deceptive request routing).

I don't think that an HTTP 403 is appropriate. My understanding is that a 403 indicates a permissions issue of some sort, such as a lack of authentication or authorization.

**Comment by kdelee** [comment]
@cdcabrera @bclarhk 

Do you guys have any opinion on this?

Hopefully we can make a decision and close this soon.

**Comment by bclarhk** [comment]
I'd prefer the results be returned along with the error. I've seen interfaces that return results but also return "Additionally an error xxx was generated by this search". 
Hopefully this never reaches the user but it will (more than likely) be helpful in development as the tool goes through iterations.

**Comment by Ichimonji10** [comment]
How can the server know what the client meant to search for if the client's search is invalid? At that point, the server is making assumptions about that the user *meant* to do, and that's an impossible game to win. I'd only recommend returning both search results and error information if a client is performing deprecated calls.

**Comment by cdcabrera** [comment]
Leading off of @bclarhk stance, it'd be nice to have both options, truly. And maybe first round as we try to integrate the UI with the API it'd be helpful. However, having dealt with long-term support of APIs I have to side with @elyezer on this. Malformed data being submitted should return an error.

Humor... we could go totally go for a the status 418

**Comment by elyezer** [comment]
@cdcabrera actually @Ichimonji10 gave me that point of view and yes I also think it makes sense

**Comment by chambrid** [comment]
If this isn’t something easily done by the Django framework I’m not planning on having the development team spend a great deal of time looking at this. First because we have many functional requirements to deliver and secondly it would seem to diverge from the expectations of the majority of community users. What does Ansible Tower do in this case, perhaps we can follow suit as this is a widely used API

**Comment by kdelee** [comment]
I talked to some Tower folks and they go with the ignore extra data/information.

Personally I side with @cdcabrera and @elyezer that malformed requests should return an error. 

But I'm willing to put this off for a very rainy day, perhaps leaving this as a very satisfactory prognostication to re-discover one day. :crystal_ball: :poop:

**Comment by Ichimonji10** [comment]
> 🔮 💩

"I look into my crystal ball, and I forsee a shitstorm over this."

**Comment by kdelee** [comment]
💯 :trollface:

**Comment by elyezer** [comment]
Another point that I think the API could be improved is by returning all field even when they are null. According to [1]:

> Some APIs do this differently. They hide the empty field entirely, removing the end_date (field on the example) key from the JSON response body. This is a bad practice. It makes the API less explorable, less self-descriptive, less predictable, and more error-prone for clients.

So making clear to the client if something is being ignored and returning all the information seems to be something that will benefit clients consuming the API.

[1] https://www.oreilly.com/ideas/how-a-restful-api-represents-resources

**Comment by kdelee** [comment]
Back here again. @elyezer 's comment about the API returing all fields would really help me with testing facts and reports.

🙏
