### ISSUE TITLE
Post processing code assumes fact value will always have a get attribute

### ISSUE THREAD

**Issue by ilyavw** [quipucords/quipucords#404]
https://github.com/quipucords/quipucords/blob/84ea5189bb9f9ec5c280d89c347b22e4b5fcd38b/quipucords/scanner/network/processing/process.py#L62

This piece of code assumes that the fact value being processed will always be a dict, or at least another data type that has a get attribute. At the same time a lot of facts come through as a `AnsibleUnsafeText` which do not have a get attribute, leading to a crash. 

Some of the fact keys that cause a crash when a post processor tries to process them are `jboss_eap_common_files`, `jboss_eap_processes`, `jboss_eap_packages`, and `jboss_eap_chkconfig`. There may be more, those are just a few that I've ran into.

**Comment by ilyavw** [comment]
fwiw, you'll run into the same issue here https://github.com/quipucords/quipucords/blob/84ea5189bb9f9ec5c280d89c347b22e4b5fcd38b/quipucords/scanner/network/processing/process.py#L67

**Comment by noahl** [comment]
Update: I've been working on reproducing this, but with no success so far. Ilya is helping me. We'll keep trying to get to the bottom of it.

**Comment by noahl** [comment]
Another update: I still don't have the exact sequence of events that lead to this, which is frustrating. However, jctanner has a pretty strong theory of the problem. Every time Ansible does templating using Jinja2, it gets the data back as a string. Ansible can then try to reconstruct Python data types, but it can only do that sometimes. It looks like Ilya's machine had a bunch of data that Ansible couldn't turn back into Python. jctanner suggests that we not use Jinja2 templating. Doing this would basically be the same as fixing https://github.com/quipucords/quipucords/issues/369 , which is a decent amount of work but which I know is possible.

Alternatively, jctanner has a pull request (https://github.com/ansible/ansible/pull/32738) out to let Ansible use native Jinja2 data types, which could also solve this problem. It looks like the plan is for it to be in Ansible 2.5 but off by default, then on by default in 2.6. Since this is a feature in the latest version of Ansible, we would essentially be committing to only shipping Sonar in a container for the next ~6 months or so, because we couldn't count on customers having a recent enough version of Ansible installed or being ready to upgrade.

**Comment by noahl** [comment]
In this case though, we only really need to make sure data is Python data types if we plan to postprocess it. I think we can say that tasks that are going to a postprocessor can't also use Jinja for now, and other tasks can.
