### ISSUE TITLE
Getting to work using minishift

### ISSUE THREAD

**Issue by ffirg** [quipucords/quipucords#580]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Low
___

## Description:
I'm trying to get this container/pipeline working inside minishift. The Jenkins node label is hardcoded to f25-os and I can't figure out what I need to change to get minishift to work.
___

### Expected behavior:
minishift deploys pipeline build

### Actual behavior:
Jenkins console output:
[Pipeline] node
Still waiting to schedule task
Jenkins doesn’t have label f25-os

### Steps to reproduce:
minishift start
oc login -u developer
oc new-project quipucords
oc new-app https://github.com/quipucords/quipucords

### Environment information:
minishift v1.12.0+daa0943
macOS 10.13.3 (High Sierra)

**Comment by elyezer** [comment]
We are running that on f25-os node because we have some packages already installed on that machine. You can see the list of installed packages here https://github.com/quipucords/ci/blob/master/ansible/roles/nodepool/files/elements/jenkins-slave/package-installs.yaml.

Also it has the jenkins user and it is setup to allow our jenkins to ssh into it and control the machine as a Jenkins slave.

If you want to run that pipeline on the Jenkins master you need to unwrap the lines from the node, for example:

```
stage('Install') {
    sh "sudo dnf -y install origin-clients"
    sh "which oc"
    sh "oc login --insecure-skip-tls-verify --token $OPENSHIFT_TOKEN $OPHENSHIFT_LOGIN_URL"
    sh "oc project quipucords"
    sh "rpm -q docker"
    sh "which docker"
    sh "echo OPTIONS=\\'--log-driver=journald\\' > /tmp/docker.conf"
    sh "echo DOCKER_CERT_PATH=/etc/docker >> /tmp/docker.conf"
    sh "echo INSECURE_REGISTRY=\\'--insecure-registry $DOCKER_REGISTRY\\' >> /tmp/docker.conf"
    sh "sudo cp /tmp/docker.conf /etc/sysconfig/docker"
    sh "cat /etc/sysconfig/docker"
    sh "sudo systemctl start docker"
    checkout scm
    sh "sleep 35s"
    sh "ps aux | grep docker"
    sh "sudo docker -v"
    sh "sudo setenforce 0"
}
stage('Build Docker Image') {
    sh "ls -lta"
    sh "cat Dockerfile"
    sh "sudo docker -D build . -t quipucords:latest"
    sh "sudo docker tag quipucords:latest $DOCKER_REGISTRY/quipucords/quipucords:latest"
    sh "sudo docker login -p $OPENSHIFT_TOKEN -u unused $DOCKER_REGISTRY"
    sh "sudo docker push $DOCKER_REGISTRY/quipucords/quipucords:latest"
}
```

With that it will run on your Jenkins master, make sure you have the packages installed because this pipeline assumes they are already installed.

**Comment by elyezer** [comment]
If you are just trying to build the Docker container then you can follow https://github.com/quipucords/quipucords#container-image instructions.

**Comment by justinkreft** [comment]
stale

**Comment by justinkreft** [comment]
stale

**Comment by justinkreft** [comment]
stale
