### ISSUE TITLE
Investigate reducing the number of commands required to install Sonar

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#786]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Low
___

## Description:
Since we have an RPM installer for qpc would it be possible to minimize the number of commands needed to get Sonar setup? For example could it create some default dirs for logs, sshkeys etc? Also could qpc come configured with a server of 127.0.0.1 as the default so that command is not required? Steps like this that we can make optional if customers are using it in a non-default manner but the RPM install could take care of a lot of the defaults.

**Comment by chambridge** [comment]
@mdvickst 
I had a random thought to try and minimize our install procedure. However, it may only work well for the pilot.

If you are familiar with how **Ansible Tower** installs this will be a similar idea. Essentially the thought is that instead of just the container on the FTP site we could have (either separate or bundled with the container image) an "Installer" of sorts. Like **Ansible Tower** we would have a playbook this playbook could attempt to automate each step within the install from downloading Docker for the appropriate version, to loading (or downloading and loading) the container image, to creating the necessary directories, optionally start the server and optionally installing the CLI and configuring it with localhost and ssl-verify=False. 

Suggested package:
- container tar.gz
- playbook and associated folders/files
- shell script to wrapper calling the playbook.

Install flow:
- enable extras and/or install EPEL
- `yum -y install ansible`
- `./install_quipucords.sh`

**Comment by mdvickst** [comment]
I think that would perfect. It does require the installation of ansible which qpc doesn't currently require but three steps is really slick. If it's bash script we could even amend it later to accept input for directory locations etc. if customers want that ability to control more of the install. I really like the idea!
