### ISSUE TITLE
Beta Docs - Scan Show/List

### ISSUE THREAD

**Issue by mdvickst** [quipucords/quipucords#788]
# Opening a new issue
___

## Specify type:
- Enhancement

### Bug severity (if applicable):
- Medium
___

## Description:
We should add a section that instructs users how to see the status of a scan
e.g.
qpc scan show --id 1

**Comment by jlprevatt** [comment]
There is an example `qpc scan show` usage in the doc. However, the title of the section in the doc where the show command is used is "viewing scan results" and the command is scan show, so really the title of the section should be changed to "showing scan results." Might bump up the findability.

In addition, the scan show scenario takes you through starting a scan, finding your scan identifier, then 
doing the scan show command, in order to explain what the scan identifier is and where it shows up as output within the active scan (at least, I assume that was Chris' intent when he put the first draft info together).

I also added a very brief scenario for the `qpc scan list` command immediately after the section on scan show; that might help:

Listing Scan Results
^^^^^^^^^^^^^^^^^^^^
In addition to showing the status of a single scan, you can also show a list of all scans that are in progress or are completed on the Quipucords server. To show this list of scans, you use the ``scan list`` command. The output of this command includes the scan identifier, the source or sources for that scan, and the current state of the scan.

  ``# qpc scan list``

**Comment by chambridge** [comment]
Following updates via:
https://github.com/quipucords/quipucords/pull/802

[Showing Scan Results for an Active Scan](
http://quipucords.readthedocs.io/en/beta/beta.html#showing-scan-results-for-an-active-scan)

[Listing Scan Results](http://quipucords.readthedocs.io/en/beta/beta.html#listing-scan-results)
