### ISSUE TITLE
Don't prompt user with help that includes invalid options

### ISSUE THREAD

**Issue by kdelee** [quipucords/quipucords#871]
# Opening a new issue
___

## Specify type:
- Bug

### Bug severity (if applicable):
- Low
___

## Description:
vCenter and Satellite type credentials cannot be made with a sshkey but if I dont pass the `--password` flag, I get help text that may lead me to think that I can do that.

### Expected behavior:
The help text does not tell me that I can do things that I cannot do.

### Actual behavior:
```bash
$ qpc cred add --name vcenter --username foo --type vcenter
usage: qpc cred add [-h] --name NAME --type TYPE --username USERNAME
                    (--password | --sshkeyfile FILENAME) [--sshpassphrase]
                    [--become-method BECOME_METHOD]
                    [--become-user BECOME_USER] [--become-password]
qpc cred add: error: one of the arguments --password --sshkeyfile is required
```

Also the case with satellite:
```
qpc cred add --name sat6 --username foo --type satellite
usage: qpc cred add [-h] --name NAME --type TYPE --username USERNAME
                    (--password | --sshkeyfile FILENAME) [--sshpassphrase]
                    [--become-method BECOME_METHOD]
                    [--become-user BECOME_USER] [--become-password]
qpc cred add: error: one of the arguments --password --sshkeyfile is required
```

### Steps to reproduce:
Attempt to add a vcenter or satellite credential and omit the `--password` flag

(installed qpc from master into virtual environment with pip)

**Comment by chambridge** [comment]
The error is output from argparser due to the mutual exclusive option of password or sshkeyfile. This is really due to the fact that we have multiple types of credentials and the CLI is meant to be dumb so its lowest common denominator. I'm gonna leave this open in case someone else on the team has an innovative way to solve it that doesn't alter the requirements (i.e. make password or sshkeyfile look optional), but otherwise while not perfect its working as designed.

**Comment by justinkreft** [comment]
Closed working as designed
